using Grasshopper;
using Rhino.Geometry;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Annotation
{
    internal static class AnnotationGuidesUtility
    {
        //public static SimpleBrepToAnnotationGuides(Brep brep, List<Plane> planes)
        //{

        //    if (Rhino.Geometry.Intersect.Intersection.BrepPlane(brep, planes[0], Utility.DocumentTolerance(), out curves, out points))
        //    {
        //        annotationGuideline.topViewCurves = curves?.ToList();
        //    }

        //    if (Rhino.Geometry.Intersect.Intersection.BrepPlane(brep, planes[1], Utility.DocumentTolerance(), out curves, out points))
        //    {
        //        annotationGuideline.frontViewCurves = curves?.ToList();
        //    }

        //    if (Rhino.Geometry.Intersect.Intersection.BrepPlane(brep, planes[2], Utility.DocumentTolerance(), out curves, out points))
        //    {
        //        annotationGuideline.rightViewCurves = curves?.ToList();
        //    }

        //    AnnotationGuides annotationGuides = 
        //}

    }
}
